---

- name: Install needed packages
  pacman:
    name: xorg-xrdb
    state: present
  sudo: yes


- name: Generate empty .Xressources file and .Xressources.d directory
  file:
    path: "{{ ansible_env.HOME }}/.Xressources"
    state: file

- file:
    path: "{{ ansible_env.HOME }}/.Xressources.d"
    state: directory

- name: Copy colors Xressources file
  copy:
    src: colors
    dest: "{{ ansible_env.HOME }}/.Xressources.d/colors"

- name: Activate colors ressources in .Xressources
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.Xressources"
    line: "#include \".Xressources.d/colors\""
    state: present

- name: Activate xrdb merge in .xinitrc file
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.xinitrc"
    line: "[[ -f ~/.Xressources ]] && xrdb -merge ~/.Xressources"
    insertbefore: "^exec"
    create: yes
    state: present
