---

- name: Update repo list
  ini_file:
    dest: /etc/pacman.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  notify: Update Pacman cache
  sudo: yes
  with_items:
    - section: archlinuxfr
      option: SigLevel
      value: Never
    - section: archlinuxfr
      option: Server
      value: http://repo.archlinux.fr/$arch

- name: Install standalone Packages
  pacman:
    name: "{{ item }}"
    state: present
  sudo: yes
  with_items: pacman_packages
