---

- name: Update repo list
  sudo: yes
  register: pacman_repositories_update
  ini_file:
    dest: /etc/pacman.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items: pacman_repositories

- name: Update Pacman cache
  sudo: yes
  when: pacman_repositories_update|changed
  pacman:
    update_cache: yes

- name: Install standalone Packages
  sudo: yes
  pacman:
    name: "{{ item }}"
    state: present
  with_items: pacman_packages
