---

- name: All configuration
  hosts: all
  gather_facts: yes
  roles:
    - { role: fonts, tags: ['fonts'] }
    - { role: xressources, tags: ['xressources'] }
    - { role: urxvt, tags: ['term', 'urxvt'] }
    - { role: zsh, tags: ['zsh'] }
    - { role: antigen, tags: ['zsh', 'antigen'] }
    - { role: spf13, tags: ['vim', 'spf13'] }
    - { role: weechat, tags: ['weechat'] }
